name: LasersEnigma-API-Usage
version: ${project.version}
main: eu.lasersenigma.apiusage.ApiUsage
api-version: 1.13
depend: [LasersEnigma]
description: A sample plugin project that uses lasers-enigma api - http://lasers-enigma.eu
website: lasers-enigma.eu
author: Lasers Enigma Team <contact@lasers-enigma.eu>
commands:
  lestats:
    description: Show players stats
    usage: /lestats [global] [top|playerName] [step|time|action]